### ISSUE TITLE
formatting error in "before insert phis" view

### ISSUE THREAD

**Issue by mark-pictor-csec** [golang-design/ssaplayground#15] opened 2022-01-27 21:45 UTC
code:
```go
package foo

func testfn() {

	var b1 string
	var b2 []byte

	_ = string(b1) == string(b2)
	_ = string(b1) < string(b2)
}
```

output `before insert phis`, line v21:
```
FwdRef <mem> {{[] %!v(PANIC=Format method: runtime error: invalid memory address or nil pointer dereference)}}
```

**Comment by changkun** [comment] 2022-01-28 08:07
I can't reproduce this. The example works well for me: https://golang.design/gossa?id=41829d7e-8011-11ec-b3e4-0242ac160010

**Comment by changkun** [comment] 2022-01-29 10:20
Close due to non-reproducible.

**Comment by mark-pictor-csec** [comment] 2022-02-02 18:56
Strange. If I run into it again, I'll see if I can get more details

**Comment by katsusan** [comment] 2022-02-09 18:28
@mark-pictor-csec the ssa view in gossa site is completely generated by go compiler, 
thus if there seems something wrong in it, you should verify it and go to official golang
issue tracker for help. You can try `GOSSAFUNC=testfn go tool compile x.go` and check
the generated ssa.html.

@changkun there is an inconspicuous error message in `before insert phis` part and 
the FwdRef is changed to a copy operation in next phase.
![image](https://user-images.githubusercontent.com/11537821/153265014-b0424601-a47b-499f-9dfb-e9372059523a.png)

I did some investigation and can be sure following code is the direct reason for the
error message, but v.Aux is `fwdRefAux` which contains a `ir.Node` member, it's too
hard for me to dig more when related to compiler typechecker.

https://github.com/golang/go/blob/master/src/cmd/compile/internal/ssa/value.go#L200-L203
```
	case auxSym, auxCall, auxTyp:
		if v.Aux != nil {
			return fmt.Sprintf(" {%v}", v.Aux)
		}
```

**Comment by changkun** [comment] 2022-02-09 18:45
Filled https://github.com/golang/go/issues/51108. Thanks @katsusan !

**Comment by changkun** [comment] 2022-03-01 18:16
Fixed on the tip. Now we can close.

**Closed as completed by changkun** 2022-03-01 18:16 UTC
Labels: bug
